import { Color } from '../enums';

export const HtmlColor: Record<Color, string> = {
  [Color.Black]: 'black',
  [Color.Blue]: 'blue',
  [Color.Blue2]: 'steelBlue',
  [Color.DullCyan]: 'cadetBlue',
  [Color.Cyan]: 'cyan',
  [Color.GrayBlue]: 'lightSteelBlue',
  [Color.Green]: 'green',
  [Color.Header]: 'yellow',
  [Color.LightBlue]: 'lightBlue',
  [Color.LightGray]: 'lightGray',
  [Color.LightGreen]: 'lightGreen',
  [Color.Lilac]: 'thistle',
  [Color.DarkOrange]: 'darkOrange',
  [Color.Orange]: 'orange',
  [Color.OrangeYellow]: 'gold',
  [Color.Purple]: 'purple',
  [Color.Red]: 'red',
  [Color.Title]: 'white',
  [Color.Turquoise]: 'turquoise',
  [Color.VividRed]: 'scarlet',
  [Color.White]: 'white',
  [Color.WhiteOrange]: 'moccasin',
  [Color.Yellow]: 'yellow',
};
