export enum Color {
  Cyan = 'C',
  DarkOrange = 'L', // dirty orange-gray
  White = 'W',
  Blue = 'B',
  Green = 'G',
  Red = 'R',
  Black = 'b',
  LightGray = 'g',
  Yellow = 'Y',
  Header = 'H',
  Title = 'T',
  Orange = 'O',
  Purple = '0',
  Lilac = '1',
  Blue2 = '2',
  GrayBlue = '3',
  LightBlue = '4',
  DullCyan = '5',
  Turquoise = '6',
  LightGreen = '7',
  OrangeYellow = '8',
  WhiteOrange = '9',
  VividRed = 't',
}
