import Head from 'next/head';
import {
  Container,
  Flex,
  Box,
  Spacer,
  Card,
  CardBody,
  Text,
  SimpleGrid,
  Stack,
  Tag,
  Tabs,
  Tab,
  Progress,
  TabPanels,
  TabPanel,
  TabList,
  Divider,
  Heading,
} from '@chakra-ui/react';
import { FC } from 'react';
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
} from '@chakra-ui/react';
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
  TagLabel,
  Tooltip,
  Button,
} from '@chakra-ui/react';

import { Input, InputGroup, InputLeftElement } from '@chakra-ui/react';
import { SearchIcon } from '@chakra-ui/icons';

const ProductCard: FC = () => {
  return (
    <Card>
      <CardBody>
        <Text>View a summary of all your customers over the last month.</Text>
      </CardBody>
    </Card>
  );
};

// Container maxW="container.xl"

export default function Home() {
  return (
    <>
      <Box width="" height={16} borderBottom="1px" borderColor="gray.200">
        <Container alignItems="center" maxW="container.xl">
          <Flex>
            <Heading>TMM</Heading>
            <Spacer />

            <Spacer />
          </Flex>
        </Container>
      </Box>
      <Box p={4}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <InputGroup size="lg">
          <InputLeftElement pointerEvents="none">
            <SearchIcon color="gray.300" />
          </InputLeftElement>
          <Input type="tel" placeholder="Search" />
        </InputGroup>

        {/*<Tooltip label="Phone number">*/}
        {/*  <Progress size="lg" value={20} />*/}
        {/*</Tooltip>*/}

        <Breadcrumb spacing={2}>
          <BreadcrumbItem>
            <BreadcrumbLink href="#">
              <Tag>
                <code>localisations</code>
              </Tag>
            </BreadcrumbLink>
          </BreadcrumbItem>

          <BreadcrumbItem isCurrentPage>
            <BreadcrumbLink href="#">
              <Tag>
                <code>linebreaks.yml</code>
              </Tag>
            </BreadcrumbLink>
          </BreadcrumbItem>
        </Breadcrumb>

        <Flex gap={4}>
          <Box flex={1}>
            <Stack spacing={3}>
              <Tabs>
                <TabList>
                  <Tab>
                    Все
                    <Tag size="sm" borderRadius="full" ml={2}>
                      99
                    </Tag>
                  </Tab>
                  <Tab>
                    Без перевода
                    <Tag size="sm" borderRadius="full" ml={2}>
                      99
                    </Tag>
                  </Tab>
                  <Tab>
                    На проверке
                    <Tag size="sm" borderRadius="full" ml={2}>
                      99
                    </Tag>
                  </Tab>
                </TabList>
              </Tabs>

              <TableContainer>
                <Table variant="striped">
                  <Thead>
                    <Tr>
                      <Th>Key</Th>
                      <Th>Text</Th>
                      <Th>Translation</Th>
                    </Tr>
                  </Thead>
                  <Tbody>
                    <Tr>
                      <Td>inches</Td>
                      <Td>millimetres (mm)</Td>
                      <Td>millimetres (mm)</Td>
                    </Tr>
                    <Tr>
                      <Td>inches</Td>
                      <Td>millimetres (mm)</Td>
                      <Td>millimetres (mm)</Td>
                    </Tr>
                    <Tr>
                      <Td>inches</Td>
                      <Td>millimetres (mm)</Td>
                      <Td>millimetres (mm)</Td>
                    </Tr>
                  </Tbody>
                </Table>
              </TableContainer>
            </Stack>
          </Box>
          <Box minW={300}></Box>
        </Flex>

        {/*<SimpleGrid columns={4} spacing={10}>*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*  <ProductCard />*/}
        {/*</SimpleGrid>*/}
      </Box>
    </>
  );
}
